/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "inverse-primary": "#ffb780",
        "on-tertiary": "#ffffff",
        "surface-container": "#edeeef",
        "on-background": "#191c1d",
        "outline": "#867468",
        "secondary": "#006c49",
        "on-primary-container": "#6f3800",
        "on-primary-fixed": "#2f1400",
        "tertiary-container": "#abadff",
        "on-tertiary-container": "#2e2dbe",
        "on-secondary-fixed": "#002113",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-primary": "#ffffff",
        "tertiary": "#494bd6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#191c1d",
        "primary-fixed-dim": "#ffb780",
        "on-surface-variant": "#534439",
        "surface-tint": "#8e4e14",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed-dim": "#4edea3",
        "surface-dim": "#d9dadb",
        "secondary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e1e0ff",
        "on-secondary": "#ffffff",
        "primary-container": "#f4a261",
        "surface-container-highest": "#e1e3e4",
        "background": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#d8c2b5",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#07006c",
        "on-secondary-container": "#00714d",
        "secondary-container": "#6cf8bb",
        "primary": "#8e4e14",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#6f3800",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed-dim": "#c0c1ff",
        "primary-fixed": "#ffdcc4"
      },
      fontFamily: {
        "label-sm": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "data-mono": ["Space Grotesk", "monospace"]
      }
    },
  },
  plugins: [],
}
